export const BASE_URL = process.env.REACT_APP_BASE_URL;
export const DESIGN_TEXT = "design";
export const FRONTEND_TEXT = "frontend";
export const BACKEND_TEXT = "backend";
export const DEVOPS_TEXT = "devops";
export const MODAL_TITLE_EDIT = "Edit Task";
export const MODAL_TITLE_CREATE = "Create Task";
export const DESIGN_BADGE_TEXT = "design-badge";
export const FRONTEND_BADGE_TEXT = "frontend-badge";
export const BACKEND_BADGE_TEXT = "backend-badge";
export const DEVOPS_BADGE_TEXT = "devops-badge";
export const TODO_STATUS_TITLE_START = "To Start";
export const TODO_STATUS_TITLE_PROGRESS = "In Progress";
export const TODO_STATUS_TITLE_DONE = "Done";
export const UPDATE_CHANGES = "Update Changes";
export const CREATE_TASK = "Create Task";
// export const TASK_STATUS_TO_BE_START = '6555b86757da404dd6aa78da'
// export const TASK_STATUS_IN_PROGRESS = '6555b8db57da404dd6aa78db'
// export const TASK_STATUS_COMPLETED = '6555b9fb57da404dd6aa78de'

export const TASK_STATUS_TO_BE_START = "65545e7b64922988e7f62563";
export const TASK_STATUS_IN_PROGRESS = "65546d5064922988e7f62564";
export const TASK_STATUS_COMPLETED = "65546d7d64922988e7f62565";
export const DROPPABLE_ID_START = "ToBeStart";
export const DROPPABLE_ID_PROGRESS = "InProgress";
export const DROPPABLE_ID_DONE = "Completed";
